[package]
name = "ios-stretch"
version = "0.1.0"
authors = ["Emil Sjölander <emil@visly.app>"]
edition = "2018"

[dependencies]
stretch = { version = "0.3.2", path = "../../.." }

[lib]
name = "stretch"
crate-type = ["staticlib"]

[workspace]
members = []
